import type { StepDefinition } from './contracts.ts'

type StepContractValue = StepDefinition['inputs'][number] | StepDefinition['outputs'][number]

function contractType(value: StepContractValue) {
  if (value.type === 'number') return 'number'
  if (value.type === 'boolean') return 'boolean'
  if (value.type === 'json') return 'unknown'
  return 'string'
}

function contractFields(values: StepDefinition['inputs'] | StepDefinition['outputs']) {
  return values
    .map(
      value => `  readonly ${value.name}${'required' in value && !value.required ? '?' : ''}: ${contractType(value)}`,
    )
    .join('\n')
}

function contractRuntime(definition: StepDefinition) {
  return definition.execution.kind === 'reviewed-extension' ? definition.execution.runtime : 'node'
}

export function generateStepDefinitionContract(definition: StepDefinition) {
  return [
    '// Generated by AppraiseJS. Changes will be overwritten.',
    `export interface StepInput {\n${contractFields(definition.inputs)}\n}`,
    `export interface StepOutput {\n${contractFields(definition.outputs)}\n}`,
    'export interface StepContext {',
    `  readonly runtime: '${contractRuntime(definition)}'`,
    '  readonly signal: AbortSignal',
    '}',
    'export type StepHandler = (input: StepInput, context: StepContext) => Promise<StepOutput>',
    '',
  ].join('\n')
}
