# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.
@ts_7f0cc2cc4b0782cv
Feature: Testing login feature

  @tc_7f0cc2cc4b0782cv
  Scenario: Testing login with valid credentials
    Given the user navigates to the base url of the selected environment
    When the user fills in the "email" input field with value "demo@example.com"
    And the user fills in the "password" input field with value "test1234"
    And the user clicks on the "Login" element
    Then the element "welcome" should true contain the text "Welcome to Home Page"
