# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

Feature: Test suite for validating navigation template steps

  @tc_bc9132db12068735
  Scenario: [Navigation by url] Test case for validating navigation to page by direct url
    Given the user navigates to the "https://demoqa.com/" url
    Then the element "header" should be visible
