# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

Feature: navigation-tests

  @tc_d7ba67225ae3d18d
  Scenario: [form test] Scenario validating random data generation and storage
    Given the user navigates to the base url of the "demoqa" environment
    When the user clicks on the "forms button" element
    And the user clicks on the "form elements" element
    And the user clicks on the "form text box" element
    And the user generates a random full name and stores it inside the variable "fullName"
    And the user fills in the "full name" input with data from the stored variable "fullName"
    And the user clicks on the "submit" element
    Then the element "form output" should contain the text inside the stored variable "fullName"
