import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { format } from 'prettier'

import {
  coordinatorOperationRegistry,
  type CoordinatorOperationId,
} from '../src/services/coordinator/coordinator-operation-registry'

type McpDefinition = { kind: 'tool' | 'resource'; name: string; description?: string; uri?: string }
type McpFixture = { default: McpDefinition[] }
export type PublicOperationReference =
  { kind: 'coordinator'; operation: CoordinatorOperationId } | { kind: 'local'; reason: string }

const localDiscoveryTools = new Set(['locator_search'])

const exactCoordinatorOperations: Readonly<Record<string, CoordinatorOperationId>> = {
  assessment_diagnose: 'quality-read',
  assessment_preflight: 'quality-read',
  assessment_readiness: 'quality-read',
  assessment_review: 'quality-read',
  evaluation_subject_remote_scope_read: 'quality-read',
  assessment_prepare_run: 'quality-write',
  environment_list: 'environment-read',
  environment_ensure: 'environment-write',
  locator_graph_query: 'locator-graph',
  locator_ensure: 'locator-write',
  project_add: 'target-project-write',
  project_diagnostic: 'diagnostic',
  project_list: 'target-projects-list',
  quality_journey_factory_evidence_inspect: 'quality-read',
  quality_journey_artifacts_list: 'quality-read',
  quality_journey_analysis_get: 'quality-read',
  quality_journey_get: 'quality-read',
  requirements_graph_read: 'quality-read',
  step_definition_draft_read: 'step-definitions-read',
  step_search: 'step-definitions-read',
  test_run_diagnose: 'test-run-evidence',
  test_run_start: 'test-run-write',
  test_run_read: 'test-run-evidence',
}

const coordinatorOperationPrefixes: ReadonlyArray<readonly [string, CoordinatorOperationId]> = [
  ['assessment_', 'quality-write'],
  ['evaluation_subject_', 'quality-write'],
  ['execution_consent_', 'quality-write'],
  ['methodology_', 'quality-read'],
  ['operation_', 'operations'],
  ['quality_journey_', 'quality-write'],
  ['requirement_analysis_', 'quality-write'],
  ['requirements_', 'quality-write'],
  ['step_definition_', 'step-definitions-write'],
  ['validation_design_', 'quality-write'],
  ['validation_', 'quality-write'],
]

export function referenceForMcpTool(name: string): PublicOperationReference {
  if (localDiscoveryTools.has(name)) return { kind: 'local', reason: 'bounded quality discovery query' }
  const exactOperation = exactCoordinatorOperations[name]
  if (exactOperation) return coordinator(exactOperation)
  const prefixOperation = coordinatorOperationPrefixes.find(([prefix]) => name.startsWith(prefix))?.[1]
  if (prefixOperation) return coordinator(prefixOperation)
  throw new Error(`MCP tool has no public operation reference: ${name}`)
}

function coordinator(operation: CoordinatorOperationId): PublicOperationReference {
  return { kind: 'coordinator', operation }
}

function escapeCell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', ' ')
}

export function generateCoordinatorReference(fixture: McpFixture): string {
  const knownOperations = new Set(coordinatorOperationRegistry.definitions.map(item => item.id))
  const definitions = fixture.default.map(item => ({ ...item, availability: 'default' }))
  const toolRows = definitions
    .filter((item): item is McpDefinition & { availability: string } => item.kind === 'tool')
    .sort((left, right) => left.name.localeCompare(right.name))
    .map(item => {
      const reference = referenceForMcpTool(item.name)
      if (reference.kind === 'coordinator' && !knownOperations.has(reference.operation))
        throw new Error(`MCP tool ${item.name} maps to missing coordinator operation ${reference.operation}.`)
      const target = reference.kind === 'coordinator' ? `\`${reference.operation}\`` : `local: ${reference.reason}`
      return `| \`${item.name}\` | ${item.availability} | ${target} | ${escapeCell(item.description ?? '')} |`
    })
  const resourceRows = definitions
    .filter((item): item is McpDefinition & { availability: string } => item.kind === 'resource')
    .sort((left, right) => left.name.localeCompare(right.name))
    .map(
      item =>
        `| \`${item.name}\` | ${item.availability} | \`${escapeCell(item.uri ?? '')}\` | ${escapeCell(item.description ?? '')} |`,
    )
  const routeRows = coordinatorOperationRegistry.definitions.map(item => {
    const route = `/api/internal/coordinator/${item.pattern.join('/')}`
    return `| \`${item.id}\` | ${item.method} | \`${route}\` |`
  })

  return `<!-- GENERATED by npm run generate:coordinator-reference. DO NOT EDIT. -->
# Public Coordinator and MCP Operation Reference

This inventory is generated from the typed coordinator operation registry and the MCP contract fixture produced by
the canonical MCP registry. Human-owned lifecycle meaning and examples remain in \`docs/coordinator-api-mcp.md\`.

## Coordinator operations

| Operation | Method | Route pattern |
| --- | --- | --- |
${routeRows.join('\n')}

## MCP tools

| Tool | Availability | Coordinator or local boundary | Description |
| --- | --- | --- | --- |
${toolRows.join('\n')}

## MCP resources

| Resource | Availability | URI | Description |
| --- | --- | --- | --- |
${resourceRows.join('\n')}
`
}

async function main(): Promise<void> {
  const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
  const fixture = JSON.parse(
    readFileSync(resolve(repoRoot, 'packages/appraisejs/src/mcp-contract.fixture.json'), 'utf8'),
  ) as McpFixture
  const outputPath = resolve(repoRoot, 'docs/generated/coordinator-operation-reference.md')
  const generated = await format(generateCoordinatorReference(fixture), { parser: 'markdown' })
  if (process.argv.includes('--check')) {
    const current = readFileSync(outputPath, 'utf8')
    if (current !== generated) throw new Error('Generated coordinator operation reference is stale.')
    console.log('Generated coordinator operation reference is current.')
    return
  }
  mkdirSync(dirname(outputPath), { recursive: true })
  writeFileSync(outputPath, generated)
  console.log(`Generated ${outputPath}.`)
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) await main()
