# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.
@ts_4d44ec70e52f33a2
Feature: This is demo one

  @tc_9c23c86d0a0bdeba
  Scenario: [Login Validation] Verify user is able to see the login page header
    Given the user navigates to the base url of the selected environment
    Then the element "Login page header" should true contain the text "Login"

  @tc_40f14dd522d7bf98
  Scenario: [Demo Test] This is a demo
    Given the user navigates to the "https://demo-test-site-beta.vercel.app" url
    When the user clicks on the "email" element

  @tc_e40594fd42874390
  Scenario: [Login Validation] Verify user is able to login the test app using valid credentials
    Given the user navigates to the base url of the selected environment
    When the user fills in the "email" input field with value "demo@example.com"
    And the user fills in the "password" input field with value "test1234"
    And the user clicks on the "submit" element
    And the user waits for the route "/home" to be loaded
    Then the element "home title" should false contain the text "Welcome to Home Page"

  @tc_8e704b788200d63e
  Scenario: [Login Validation 1] Verify user is able to login the test app using valid credentials
    Given the user navigates to the base url of the selected environment
    When the user fills in the "email" input field with value "demo@example.com"
    And the user fills in the "password" input field with value "test1234"
    And the user clicks on the "submit" element
    And the user waits for the route "/home" to be loaded
    Then the element "home title" should false contain the text "Welcome to Home Page"

  @tc_8e704b788200d64e
  Scenario: [Login Validation 2] Verify user is able to login the test app using valid credentials
    Given the user navigates to the base url of the selected environment
    When the user fills in the "email" input field with value "demo@example.com"
    And the user fills in the "password" input field with value "test1234"
    And the user clicks on the "submit" element
    And the user waits for the route "/home" to be loaded
    Then the element "home title" should false contain the text "Welcome to Home Page"

  @tc_8e704b788200d65e
  Scenario: [Login Validation 3] Verify user is able to login the test app using valid credentials
    Given the user navigates to the base url of the selected environment
    When the user fills in the "email" input field with value "demo@example.com"
    And the user fills in the "password" input field with value "test1234"
    And the user clicks on the "submit" element
    And the user waits for the route "/home" to be loaded
    Then the element "home title" should false contain the text "Welcome to Home Page"
