# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

Feature: Collection of test cases covering login scenarios

  Scenario: [Long wait validation for login] Login Long
    Given the user navigates to the "staging" environment
    When the user waits for 10 seconds
    Then the user should be navigated to the "/login" route

  Scenario: [Verify the user is able to navigate to the login page of staging environmnet] Login
    Given the user navigates to the "staging" environment
    Then the user should be navigated to the "/login" route

  Scenario: [Validate failure scenario for login validation step] Failing Login
    Given the user navigates to the "staging" environment
    Then the user should be navigated to the "/test" route
