# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

@run
Feature: Collection of test cases covering login scenarios

  @tc_4rswpaiw
  Scenario: [Validate user is failing to login when being navigated to incorrect route] Failing Login
    Given the user navigates to the "staging" environment
    Then the user should be navigated to the "/test" route

  @tc_clurjmcu
  Scenario: [Verify user is able to login to the application using valid login credentials] Login
    Given the user navigates to the "staging" environment
    Then the user should be navigated to the "/login" route
