# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

@run
Feature: test 12313021sada

  @tc_4rswpaiw
  Scenario: [Failing Login] Validate user is failing to login when being navigated to incorrect route
    Given the user navigates to the "staging" environment
    Then the user should be navigated to the "/test" route
