# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

@run
Feature: Collection of test cases covering login scenarios

  @tc_qng7yehh
  Scenario: [Login] Verify the user is able to navigate to the login page of staging environmnet
    Given the user navigates to the "staging" environment
    Then the user should be navigated to the "/login" route
