# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

@run
Feature: Collection of test scenarios validating login scenarios

  @tc_3f971cb27c8b7a92
  Scenario: [Login] Validate user can navigate to the login route
    Given the user navigates to the "staging" environment
    Then the user should be navigated to the "/login" route

  @tc_f7842cdd05aa5fd7
  Scenario: [Failing Login] Failing login scenario
    Given the user navigates to the "staging" environment
    Then the user should be navigated to the "/test" route
