# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

Feature: login

  @tc_076b9e46c0fa1586
  Scenario: [navigation] validate user is able to navigate to the login page of the environment
    Given the user navigates to the base url of the selected environment
    Then the url route should be equal to "/login"

  @tc_2d1e1128876ce9d5
  Scenario: [login] validate user is able to login to app using valid credentials
    Given the user navigates to the "https://demo-test-site-beta.vercel.app" url
    When the user fills in the "email" input field with value "demo@example.com"
    And the user fills in the "password" input field with value "test1234"
    And the user clicks on the "submit" element
    Then the element "home title" should true contain the text "Welcome to Home Page"
