import { Report, Tag, ReportTestCase, TestRun, TestRunTestCase, TestCase, TestRunTestCaseStatus, TestRunStatus, TestRunResult, TagType } from '@prisma/client'

export const sampleReportData: (Report & {
  testRun: TestRun
  tags?: Tag[]
  reportTestCases: (ReportTestCase & {
    testRunTestCase: TestRunTestCase
    testCase: TestCase & { tags?: Tag[] }
  })[]
})[] = [
  {
    id: 'report-1',
    name: 'Test Run Report - Login Flow',
    description: 'Report for login functionality test run',
    createdAt: new Date('2024-01-15T10:00:00Z'),
    updatedAt: new Date('2024-01-15T10:30:00Z'),
    testRunId: 'test-run-1',
    testRun: {
      id: 'test-run-1',
      name: 'Login Flow Test Run',
      runId: 'run-uuid-1',
      startedAt: new Date('2024-01-15T09:00:00Z'),
      completedAt: new Date('2024-01-15T10:00:00Z'),
      status: TestRunStatus.COMPLETED,
      result: TestRunResult.PASSED,
      updatedAt: new Date('2024-01-15T10:00:00Z'),
      environmentId: 'env-1',
      testWorkersCount: 2,
      browserEngine: 'CHROMIUM',
      logPath: '/logs/test-run-1.log',
    },
    tags: [
      {
        id: 'tag-1',
        name: 'smoke',
        tagExpression: '@smoke',
        type: TagType.FILTER,
        createdAt: new Date('2024-01-01T00:00:00Z'),
        updatedAt: new Date('2024-01-01T00:00:00Z'),
      },
    ],
    reportTestCases: [
      {
        id: 'report-test-case-1',
        reportId: 'report-1',
        testCaseId: 'test-case-1',
        testRunTestCaseId: 'test-run-test-case-1',
        duration: 1250,
        testRunTestCase: {
          id: 'test-run-test-case-1',
          testRunId: 'test-run-1',
          testCaseId: 'test-case-1',
          status: TestRunTestCaseStatus.COMPLETED,
          result: 'PASSED',
          tracePath: '/traces/test-case-1.json',
        },
        testCase: {
          id: 'test-case-1',
          title: 'User Login with Valid Credentials',
          description: 'Verify that a user can successfully log in with valid credentials',
          createdAt: new Date('2024-01-10T08:00:00Z'),
          updatedAt: new Date('2024-01-10T08:00:00Z'),
          tags: [
            {
              id: 'tag-2',
              name: 'authentication',
              tagExpression: '@authentication',
              type: TagType.IDENTIFIER,
              createdAt: new Date('2024-01-01T00:00:00Z'),
              updatedAt: new Date('2024-01-01T00:00:00Z'),
            },
            {
              id: 'tag-3',
              name: 'critical',
              tagExpression: '@critical',
              type: TagType.FILTER,
              createdAt: new Date('2024-01-01T00:00:00Z'),
              updatedAt: new Date('2024-01-01T00:00:00Z'),
            },
          ],
        },
      },
    ],
  },
  {
    id: 'report-2',
    name: 'Test Run Report - Checkout Process',
    description: 'Report for checkout functionality test run',
    createdAt: new Date('2024-01-16T14:00:00Z'),
    updatedAt: new Date('2024-01-16T14:45:00Z'),
    testRunId: 'test-run-2',
    testRun: {
      id: 'test-run-2',
      name: 'Checkout Process Test Run',
      runId: 'run-uuid-2',
      startedAt: new Date('2024-01-16T13:00:00Z'),
      completedAt: new Date('2024-01-16T14:00:00Z'),
      status: TestRunStatus.COMPLETED,
      result: TestRunResult.FAILED,
      updatedAt: new Date('2024-01-16T14:00:00Z'),
      environmentId: 'env-2',
      testWorkersCount: 1,
      browserEngine: 'FIREFOX',
      logPath: '/logs/test-run-2.log',
    },
    tags: [],
    reportTestCases: [
      {
        id: 'report-test-case-2',
        reportId: 'report-2',
        testCaseId: 'test-case-2',
        testRunTestCaseId: 'test-run-test-case-2',
        duration: 3450,
        testRunTestCase: {
          id: 'test-run-test-case-2',
          testRunId: 'test-run-2',
          testCaseId: 'test-case-2',
          status: TestRunTestCaseStatus.COMPLETED,
          result: 'FAILED',
          tracePath: '/traces/test-case-2.json',
        },
        testCase: {
          id: 'test-case-2',
          title: 'Complete Checkout with Credit Card',
          description: 'Verify that a user can complete checkout using a credit card',
          createdAt: new Date('2024-01-11T09:00:00Z'),
          updatedAt: new Date('2024-01-11T09:00:00Z'),
          tags: [
            {
              id: 'tag-4',
              name: 'payment',
              tagExpression: '@payment',
              type: TagType.IDENTIFIER,
              createdAt: new Date('2024-01-01T00:00:00Z'),
              updatedAt: new Date('2024-01-01T00:00:00Z'),
            },
          ],
        },
      },
    ],
  },
  {
    id: 'report-3',
    name: 'Test Run Report - Search Functionality',
    description: 'Report for search feature test run',
    createdAt: new Date('2024-01-17T11:00:00Z'),
    updatedAt: new Date('2024-01-17T11:20:00Z'),
    testRunId: 'test-run-3',
    testRun: {
      id: 'test-run-3',
      name: 'Search Functionality Test Run',
      runId: 'run-uuid-3',
      startedAt: new Date('2024-01-17T10:00:00Z'),
      completedAt: null,
      status: TestRunStatus.RUNNING,
      result: TestRunResult.PENDING,
      updatedAt: new Date('2024-01-17T11:00:00Z'),
      environmentId: 'env-1',
      testWorkersCount: 3,
      browserEngine: 'WEBKIT',
      logPath: '/logs/test-run-3.log',
    },
    tags: [
      {
        id: 'tag-5',
        name: 'regression',
        tagExpression: '@regression',
        type: TagType.FILTER,
        createdAt: new Date('2024-01-01T00:00:00Z'),
        updatedAt: new Date('2024-01-01T00:00:00Z'),
      },
    ],
    reportTestCases: [
      {
        id: 'report-test-case-3',
        reportId: 'report-3',
        testCaseId: 'test-case-3',
        testRunTestCaseId: 'test-run-test-case-3',
        duration: 890,
        testRunTestCase: {
          id: 'test-run-test-case-3',
          testRunId: 'test-run-3',
          testCaseId: 'test-case-3',
          status: TestRunTestCaseStatus.RUNNING,
          result: 'UNTESTED',
          tracePath: null,
        },
        testCase: {
          id: 'test-case-3',
          title: 'Search Products by Keyword',
          description: 'Verify that users can search for products using keywords',
          createdAt: new Date('2024-01-12T10:00:00Z'),
          updatedAt: new Date('2024-01-12T10:00:00Z'),
          tags: [],
        },
      },
    ],
  },
  {
    id: 'report-4',
    name: 'Test Run Report - User Profile Update',
    description: 'Report for user profile update test run',
    createdAt: new Date('2024-01-18T15:00:00Z'),
    updatedAt: new Date('2024-01-18T15:15:00Z'),
    testRunId: 'test-run-4',
    testRun: {
      id: 'test-run-4',
      name: 'User Profile Update Test Run',
      runId: 'run-uuid-4',
      startedAt: new Date('2024-01-18T14:00:00Z'),
      completedAt: new Date('2024-01-18T15:00:00Z'),
      status: TestRunStatus.COMPLETED,
      result: TestRunResult.PASSED,
      updatedAt: new Date('2024-01-18T15:00:00Z'),
      environmentId: 'env-1',
      testWorkersCount: 2,
      browserEngine: 'CHROMIUM',
      logPath: '/logs/test-run-4.log',
    },
    tags: [],
    reportTestCases: [
      {
        id: 'report-test-case-4',
        reportId: 'report-4',
        testCaseId: 'test-case-4',
        testRunTestCaseId: 'test-run-test-case-4',
        duration: 2100,
        testRunTestCase: {
          id: 'test-run-test-case-4',
          testRunId: 'test-run-4',
          testCaseId: 'test-case-4',
          status: TestRunTestCaseStatus.COMPLETED,
          result: 'PASSED',
          tracePath: '/traces/test-case-4.json',
        },
        testCase: {
          id: 'test-case-4',
          title: 'Update User Profile Information',
          description: 'Verify that users can update their profile information',
          createdAt: new Date('2024-01-13T11:00:00Z'),
          updatedAt: new Date('2024-01-13T11:00:00Z'),
          tags: [
            {
              id: 'tag-6',
              name: 'user-management',
              tagExpression: '@user-management',
              type: TagType.IDENTIFIER,
              createdAt: new Date('2024-01-01T00:00:00Z'),
              updatedAt: new Date('2024-01-01T00:00:00Z'),
            },
            {
              id: 'tag-7',
              name: 'smoke',
              tagExpression: '@smoke',
              type: TagType.FILTER,
              createdAt: new Date('2024-01-01T00:00:00Z'),
              updatedAt: new Date('2024-01-01T00:00:00Z'),
            },
          ],
        },
      },
    ],
  },
  {
    id: 'report-5',
    name: 'Test Run Report - Password Reset',
    description: 'Report for password reset functionality test run',
    createdAt: new Date('2024-01-19T09:00:00Z'),
    updatedAt: new Date('2024-01-19T09:10:00Z'),
    testRunId: 'test-run-5',
    testRun: {
      id: 'test-run-5',
      name: 'Password Reset Test Run',
      runId: 'run-uuid-5',
      startedAt: new Date('2024-01-19T08:00:00Z'),
      completedAt: new Date('2024-01-19T09:00:00Z'),
      status: TestRunStatus.COMPLETED,
      result: TestRunResult.PASSED,
      updatedAt: new Date('2024-01-19T09:00:00Z'),
      environmentId: 'env-2',
      testWorkersCount: 1,
      browserEngine: 'CHROMIUM',
      logPath: '/logs/test-run-5.log',
    },
    tags: [],
    reportTestCases: [
      {
        id: 'report-test-case-5',
        reportId: 'report-5',
        testCaseId: 'test-case-5',
        testRunTestCaseId: 'test-run-test-case-5',
        duration: 1560,
        testRunTestCase: {
          id: 'test-run-test-case-5',
          testRunId: 'test-run-5',
          testCaseId: 'test-case-5',
          status: TestRunTestCaseStatus.COMPLETED,
          result: 'PASSED',
          tracePath: '/traces/test-case-5.json',
        },
        testCase: {
          id: 'test-case-5',
          title: 'Reset Password via Email',
          description: 'Verify that users can reset their password using email',
          createdAt: new Date('2024-01-14T12:00:00Z'),
          updatedAt: new Date('2024-01-14T12:00:00Z'),
          tags: [
            {
              id: 'tag-8',
              name: 'authentication',
              tagExpression: '@authentication',
              type: TagType.IDENTIFIER,
              createdAt: new Date('2024-01-01T00:00:00Z'),
              updatedAt: new Date('2024-01-01T00:00:00Z'),
            },
          ],
        },
      },
    ],
  },
]

