import type { StepDefinition } from '../../../../packages/cucumber-runtime/src/step-definitions/index'

export type DraftDefinition = StepDefinition

export function namedPlaceholders(signature: string) {
  return [...signature.matchAll(/\{([a-z][a-zA-Z0-9-]*)\}/g)].map(match => match[1]!)
}

export function reconcileNamedInputs(definition: DraftDefinition, signature: string): DraftDefinition {
  const placeholders = [...new Set(namedPlaceholders(signature))]
  const existing = new Map(definition.inputs.map(input => [input.name, input]))
  const inputs = placeholders.map(
    name =>
      existing.get(name) ?? {
        name,
        label: name,
        description: `Value for ${name}.`,
        type: 'string' as const,
        required: true,
        examples: [],
        aliases: [],
      },
  )
  return {
    ...definition,
    inputs,
    human: {
      ...definition.human,
      signature,
      parameterBindings: placeholders.map(name => ({ placeholder: name, input: name })),
    },
  }
}

export function createHumanStepDraft(now = new Date().toISOString()): DraftDefinition {
  const emptyHash = `sha256:${'0'.repeat(64)}` as const
  return {
    schemaVersion: '1',
    identity: { id: 'custom.new-step', version: '1', status: 'draft' },
    provenance: { creationMethod: 'human-form', createdBy: 'local-user', createdAt: now },
    intent: {
      title: 'New reusable step',
      description: 'Describe the reusable behavior.',
      capabilities: ['node'],
      searchTerms: [],
      examples: ['Describe one intended use.'],
    },
    inputs: [],
    outputs: [],
    human: {
      signature: 'I perform a reusable behavior',
      keywordCompatibility: ['When'],
      parameterBindings: [],
      groupId: 'custom',
    },
    agent: {
      summary: 'Perform the reusable behavior.',
      usageGuidance: 'Use when this exact reusable behavior is required.',
      examples: [{ intent: 'Use the reusable behavior', inputs: {} }],
    },
    execution: {
      kind: 'reviewed-extension',
      extensionId: 'custom.new-step',
      extensionVersion: '1',
      exportName: 'handler',
      sourceHash: emptyHash,
      compiledHash: emptyHash,
      runtime: 'node',
    },
    lifecycle: {},
  }
}

function contractType(input: DraftDefinition['inputs'][number] | DraftDefinition['outputs'][number]) {
  if (input.type === 'number') return 'number'
  if (input.type === 'boolean') return 'boolean'
  if (input.type === 'json') return 'unknown'
  return 'string'
}

// fallow-ignore-next-line code-duplication -- Client-safe projection mirrors the server generator without importing server dependencies.
export function draftContractSource(definition: DraftDefinition) {
  const fields = (values: DraftDefinition['inputs'] | DraftDefinition['outputs']) =>
    values
      .map(
        value => `  readonly ${value.name}${'required' in value && !value.required ? '?' : ''}: ${contractType(value)}`,
      )
      .join('\n')
  return [
    '// Generated by AppraiseJS. Changes will be overwritten.',
    `export interface StepInput {\n${fields(definition.inputs)}\n}`,
    `export interface StepOutput {\n${fields(definition.outputs)}\n}`,
    'export interface StepContext {',
    `  readonly runtime: '${definition.execution.kind === 'reviewed-extension' ? definition.execution.runtime : 'node'}'`,
    '  readonly signal: AbortSignal',
    '}',
    'export type StepHandler = (input: StepInput, context: StepContext) => Promise<StepOutput>',
    '',
  ].join('\n')
}

export function draftHandlerBoilerplate(definition: DraftDefinition) {
  const outputs = definition.outputs.map(output => `${output.name}: undefined as never`).join(', ')
  return [
    "import type { StepHandler } from './contract.js'",
    '',
    'export const handler: StepHandler = async (input, context) => {',
    '  void input',
    '  context.signal.throwIfAborted()',
    '  // Implement the reviewed behavior here.',
    `  return { ${outputs} }`,
    '}',
    '',
  ].join('\n')
}
