import type { JourneyCommand, JourneyWorkItemStatus, QualityJourneyRole, QualityJourneyStage } from './contracts'

type JourneyTransition = {
  from: QualityJourneyStage
  command: JourneyCommand['command']
  actor: 'USER' | 'RUNNER' | 'MANAGED_RUNTIME'
  to: QualityJourneyStage
  requiredArtifacts: readonly string[]
  forbiddenCapabilities: readonly string[]
  failureCodes: readonly string[]
}

export const qualityJourneyTransitions = [
  {
    from: 'INTAKE',
    command: 'SUBMIT_REQUIREMENT',
    actor: 'USER',
    to: 'ANALYSIS',
    requiredArtifacts: ['JOURNEY_REVISION'],
    forbiddenCapabilities: ['infer target binding'],
    failureCodes: ['TARGET_NOT_BOUND', 'STALE_STATE_HASH'],
  },
  {
    from: 'ANALYSIS',
    command: 'PUBLISH_ANALYSIS',
    actor: 'RUNNER',
    to: 'ANALYSIS_REVIEW',
    requiredArtifacts: ['ANALYSIS_CHARTER_REVISION'],
    forbiddenCapabilities: ['self-approve analysis'],
    failureCodes: ['REQUIRED_QUESTION_MISSING', 'STALE_INPUT'],
  },
  {
    from: 'ANALYSIS_REVIEW',
    command: 'DECIDE_ANALYSIS',
    actor: 'USER',
    to: 'DISCOVERY',
    requiredArtifacts: ['ANALYSIS_CHARTER_REVISION', 'JOURNEY_APPROVAL'],
    forbiddenCapabilities: ['approve superseded revision'],
    failureCodes: ['UNRESOLVED_REQUIRED_QUESTION', 'REVISION_SUPERSEDED'],
  },
  {
    from: 'DISCOVERY',
    command: 'START_SCENARIO_DESIGN',
    actor: 'RUNNER',
    to: 'SCENARIO_DESIGN',
    requiredArtifacts: ['TARGET_OBSERVATION_BUNDLE', 'RESOURCE_RESOLUTION_BUNDLE'],
    forbiddenCapabilities: ['broaden approved target scope'],
    failureCodes: ['DISCOVERY_INCOMPLETE', 'OBSERVATION_STALE'],
  },
  {
    from: 'SCENARIO_DESIGN',
    command: 'PUBLISH_SCENARIO_PORTFOLIO',
    actor: 'RUNNER',
    to: 'SCENARIO_REVIEW',
    requiredArtifacts: ['SCENARIO_PORTFOLIO_REVISION'],
    forbiddenCapabilities: ['invent target facts'],
    failureCodes: ['REQUIREMENT_TRACEABILITY_MISSING'],
  },
  {
    from: 'SCENARIO_REVIEW',
    command: 'DECIDE_SCENARIOS',
    actor: 'USER',
    to: 'AUTOMATION',
    requiredArtifacts: ['SCENARIO_PORTFOLIO_REVISION', 'JOURNEY_APPROVAL'],
    forbiddenCapabilities: ['approve rejected scenario revisions'],
    failureCodes: ['NO_SCENARIO_APPROVED', 'REVISION_SUPERSEDED'],
  },
  {
    from: 'AUTOMATION',
    command: 'START_EXECUTION',
    actor: 'RUNNER',
    to: 'EXECUTION',
    requiredArtifacts: ['RUNTIME_CAPSULE'],
    forbiddenCapabilities: ['change approved behavioral intent'],
    failureCodes: ['MATERIALIZATION_INCOMPLETE', 'EXECUTION_CONSENT_REQUIRED'],
  },
  {
    from: 'EXECUTION',
    command: 'PUBLISH_RUN_RESULT',
    actor: 'MANAGED_RUNTIME',
    to: 'TRIAGE',
    requiredArtifacts: ['TEST_RUN', 'EVIDENCE_RECEIPT'],
    forbiddenCapabilities: ['rewrite sealed evidence'],
    failureCodes: ['RUN_NOT_SEALED', 'EVIDENCE_INCOMPLETE'],
  },
  {
    from: 'TRIAGE',
    command: 'START_RERUN_CYCLE',
    actor: 'USER',
    to: 'EXECUTION',
    requiredArtifacts: ['TEST_RUN', 'EVIDENCE_RECEIPT'],
    forbiddenCapabilities: ['rewrite predecessor execution evidence'],
    failureCodes: ['RERUN_SCOPE_NOT_APPROVED', 'STALE_STATE_HASH'],
  },
  {
    from: 'TRIAGE',
    command: 'PUBLISH_TRIAGE_REPORT',
    actor: 'RUNNER',
    to: 'REPORT_REVIEW',
    requiredArtifacts: ['TEST_REPORT_ANALYSIS_REVISION'],
    forbiddenCapabilities: ['modify automation while attributing the run'],
    failureCodes: ['FAILURE_UNATTRIBUTED', 'EVIDENCE_SCOPE_MISMATCH'],
  },
  {
    from: 'REPORT_REVIEW',
    command: 'CLOSE_JOURNEY',
    actor: 'USER',
    to: 'CLOSED',
    requiredArtifacts: ['TEST_REPORT_ANALYSIS_REVISION', 'JOURNEY_CLOSURE'],
    forbiddenCapabilities: ['silently accept unresolved risk'],
    failureCodes: ['UNRESOLVED_ITEMS', 'REPORT_SUPERSEDED'],
  },
  {
    from: 'REPORT_REVIEW',
    command: 'RISK_ACCEPT_AND_CLOSE',
    actor: 'USER',
    to: 'CLOSED',
    requiredArtifacts: ['TEST_REPORT_ANALYSIS_REVISION', 'JOURNEY_CLOSURE'],
    forbiddenCapabilities: ['omit risk rationale'],
    failureCodes: ['RISK_ACCEPTANCE_INCOMPLETE', 'REPORT_SUPERSEDED'],
  },
  {
    from: 'ANALYSIS_REVIEW',
    command: 'REQUEST_ANALYSIS_REVISION',
    actor: 'USER',
    to: 'ANALYSIS',
    requiredArtifacts: ['ANALYSIS_CHARTER_REVISION'],
    forbiddenCapabilities: ['mutate reviewed revision'],
    failureCodes: ['REVISION_SUPERSEDED'],
  },
  {
    from: 'DISCOVERY',
    command: 'RETRY_DISCOVERY',
    actor: 'RUNNER',
    to: 'DISCOVERY',
    requiredArtifacts: ['JOURNEY_REVISION'],
    forbiddenCapabilities: ['reopen approved analysis without requirement ambiguity'],
    failureCodes: ['RETRY_SCOPE_INVALID'],
  },
  {
    from: 'SCENARIO_REVIEW',
    command: 'REQUEST_SCENARIO_REVISION',
    actor: 'USER',
    to: 'SCENARIO_DESIGN',
    requiredArtifacts: ['SCENARIO_PORTFOLIO_REVISION'],
    forbiddenCapabilities: ['mutate reviewed scenario revision'],
    failureCodes: ['REVISION_SUPERSEDED'],
  },
  {
    from: 'AUTOMATION',
    command: 'RETRY_AUTOMATION',
    actor: 'RUNNER',
    to: 'AUTOMATION',
    requiredArtifacts: ['SCENARIO_REVISION'],
    forbiddenCapabilities: ['alter approved scenario intent'],
    failureCodes: ['APPROVED_INTENT_CHANGED'],
  },
  {
    from: 'REPORT_REVIEW',
    command: 'REQUEST_REPORT_REVISION',
    actor: 'USER',
    to: 'TRIAGE',
    requiredArtifacts: ['TEST_REPORT_ANALYSIS_REVISION'],
    forbiddenCapabilities: ['mutate reviewed report revision'],
    failureCodes: ['REPORT_SUPERSEDED'],
  },
  {
    from: 'REPORT_REVIEW',
    command: 'START_REMEDIATION_CYCLE',
    actor: 'USER',
    to: 'AUTOMATION',
    requiredArtifacts: ['TEST_REPORT_ANALYSIS_REVISION'],
    forbiddenCapabilities: ['rewrite predecessor cycle evidence'],
    failureCodes: ['REMEDIATION_SCOPE_REQUIRED'],
  },
  {
    from: 'DISCOVERY',
    command: 'RESUME_BLOCKER',
    actor: 'USER',
    to: 'DISCOVERY',
    requiredArtifacts: ['JOURNEY_REVISION'],
    forbiddenCapabilities: ['resume without exact blocker resolution'],
    failureCodes: ['BLOCKER_NOT_RESOLVED'],
  },
] as const satisfies readonly JourneyTransition[]

export const workItemTransitions: Readonly<Record<JourneyWorkItemStatus, readonly JourneyWorkItemStatus[]>> = {
  ELIGIBLE: ['WORK_ITEM_ISSUED', 'CANCELLED', 'SUPERSEDED'],
  WORK_ITEM_ISSUED: ['WORKER_REQUESTED', 'CANCELLED', 'SUPERSEDED'],
  WORKER_REQUESTED: ['WORKER_STARTED', 'BLOCKED', 'CANCELLED'],
  WORKER_STARTED: ['IN_PROGRESS', 'LEASE_EXPIRED', 'BLOCKED'],
  IN_PROGRESS: ['QUESTION_RAISED', 'OUTPUT_SUBMITTED', 'BLOCKED', 'LEASE_EXPIRED'],
  QUESTION_RAISED: ['WAITING_FOR_INPUT', 'IN_PROGRESS', 'BLOCKED'],
  WAITING_FOR_INPUT: ['IN_PROGRESS', 'CANCELLED', 'SUPERSEDED'],
  OUTPUT_SUBMITTED: ['OUTPUT_VALIDATED', 'REVISION_REQUIRED', 'BLOCKED'],
  OUTPUT_VALIDATED: ['COMPLETED', 'REVISION_REQUIRED'],
  COMPLETED: [],
  BLOCKED: ['IN_PROGRESS', 'ESCALATED', 'CANCELLED'],
  ESCALATED: ['IN_PROGRESS', 'CANCELLED', 'SUPERSEDED'],
  LEASE_EXPIRED: ['REPLACEMENT_REQUESTED', 'CANCELLED'],
  REPLACEMENT_REQUESTED: ['WORKER_REQUESTED', 'CANCELLED'],
  REVISION_REQUIRED: ['WORKER_REQUESTED', 'CANCELLED', 'SUPERSEDED'],
  CANCELLED: [],
  SUPERSEDED: [],
}

export const stageRoleEligibility: Readonly<Partial<Record<QualityJourneyStage, readonly QualityJourneyRole[]>>> = {
  ANALYSIS: ['REQUIREMENT_ANALYZER'],
  DISCOVERY: ['SCOUT', 'RESOURCE_EXPLORER'],
  SCENARIO_DESIGN: ['TEST_SCENARIO_DESIGNER'],
  AUTOMATION: ['AUTOMATOR'],
  TRIAGE: ['TRIAGER'],
}
