# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

@demo
Feature: teasd

  Scenario: [asdasd] asdsadasd
    Given Given the user navigates to "asdsad"
    When Given the user navigates to "asdasd"
