# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

Feature: click

  @tc_de5872210197f95f
  Scenario: [Click Test] Test for validating click actions
    Given the user navigates to the base url of the "demoqa" environment
    When the user clicks on the "elements" element
    And the user clicks on the "buttons" element
    And the user clicks on the "click me" element
    Then the visibility status of the "dynamic click message" element should be true
