# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

Feature: click

  @tc_048bb41f23da9e92
  Scenario: [store test] test scenario for validating store step
    Given the user navigates to the base url of the "demoqa" environment
    When the user stores the "elements text" element text and stores it in variable "test"
