# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

@ts_ed58d77414e50588
Feature: Login 

  @tc_e433a5080c21100c
  Scenario: [Login] Login with valid credentials
    Given the user navigates to the base url of the selected environment
    When the user fills in the "Email" input field with value "demo@example.com"
    And the user fills in the "Password" input field with value "test1234"
    And the user clicks on the "Login" element
    And the user waits for the route "/home" to be loaded
    Then the element "Home Title" should true contain the text "Welcome to Home Page"
