# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

@lemon
Feature: adasdasd

  @tc_e40594fd42874390
  Scenario: [Login Validation] Verify user is able to login the test app using valid credentials
    Given the user navigates to the base url of the selected environment
    When the user fills in the "email" input field with value "demo@example.com"
    And the user fills in the "password" input field with value "test1234"
    And the user clicks on the "submit" element
    And the user waits for the route "/home" to be loaded
    Then the element "home title" should false contain the text "Welcome to Home Page"
