# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

@auth
@ts_0f27b215d17bf42e
Feature: Verify user login flows

  @tc_c943885716196fa8
  Scenario: [test] asdasd
    Given the element "Email" should have active status false
    When the user clicks on the "Home Title" element
