import { promises as fs } from 'fs'
import { join, dirname } from 'path'
import prisma from '@/config/db-config'
import { buildModulePath } from '@/lib/path-helpers/module-path'
import { getAutomationFeaturesDir } from '@/lib/automation/automation-path-roots'
import { ensureAutomationWorkspaceReady } from '@/lib/automation/automation-workspace'
import { generateProjectedGherkinSteps, getTestSuiteFilesystemKey } from '@/lib/sync/projected-feature-utils'

async function isDirectoryEmpty(dirPath: string): Promise<boolean> {
  try {
    const entries = await fs.readdir(dirPath)
    return entries.length === 0
  } catch {
    return true
  }
}

async function removeEmptyDirectoriesUp(dirPath: string, basePath: string): Promise<void> {
  let currentPath = dirPath

  while (currentPath !== basePath && currentPath !== dirname(currentPath)) {
    try {
      if (await isDirectoryEmpty(currentPath)) {
        await fs.rmdir(currentPath)
        currentPath = dirname(currentPath)
      } else {
        break
      }
    } catch {
      break
    }
  }
}

export async function generateFeatureFile(
  testSuiteId: string,
  testSuiteName: string,
  testSuiteDescription?: string,
): Promise<string> {
  try {
    await ensureAutomationWorkspaceReady()
    const [testSuite, allModules] = await Promise.all([
      prisma.testSuite.findUnique({
        where: { id: testSuiteId },
        include: {
          testCases: {
            include: {
              steps: {
                include: {
                  parameters: true,
                },
                orderBy: {
                  order: 'asc',
                },
              },
              tags: true,
            },
          },
          module: true,
          tags: true,
        },
      }),
      prisma.module.findMany(),
    ])

    if (!testSuite) {
      throw new Error(`Test suite with ID ${testSuiteId} not found`)
    }

    const modulePath = buildModulePath(allModules, testSuite.module)
    const featureContent = generateFeatureContent(
      testSuiteDescription || testSuiteName,
      testSuite.testCases,
      testSuite.tags,
    )

    const featuresBaseDir = getAutomationFeaturesDir()
    const moduleDir = join(featuresBaseDir, modulePath.substring(1))
    await fs.mkdir(moduleDir, { recursive: true })

    const safeFileName = getTestSuiteFilesystemKey(testSuiteName)
    const featureFilePath = join(moduleDir, `${safeFileName}.feature`)

    await fs.writeFile(featureFilePath, featureContent, 'utf8')
    return featureFilePath
  } catch (error) {
    console.error('Error generating feature file:', error)
    throw error
  }
}

function generateFeatureContent(
  featureTitle: string,
  testCases: Array<{
    title: string
    description: string
    steps: Array<{
      gherkinStep: string
      order: number
    }>
    tags?: Array<{
      tagExpression: string
    }>
  }>,
  testSuiteTags?: Array<{
    tagExpression: string
  }>,
): string {
  const lines: string[] = []

  lines.push('# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY')
  lines.push('# This file is automatically generated from Test Suite data.')
  lines.push('# Any manual changes will be overwritten when the Test Suite is updated.')
  lines.push('# To modify this feature, update the corresponding Test Suite in the application.')
  lines.push('')

  if (testSuiteTags && testSuiteTags.length > 0) {
    testSuiteTags.forEach(tag => {
      lines.push(tag.tagExpression)
    })
  }

  lines.push(`Feature: ${featureTitle}`)
  lines.push('')

  const testSuiteTagExpressions = new Set((testSuiteTags || []).map(tag => tag.tagExpression.toLowerCase()))
  let scenarioCount = 0

  testCases.forEach(testCase => {
    if (testCase.steps && testCase.steps.length > 0) {
      const gherkinSteps = generateProjectedGherkinSteps(testCase.steps)

      if (gherkinSteps.length > 0) {
        if (scenarioCount > 0) {
          lines.push('')
        }

        if (testCase.tags && testCase.tags.length > 0) {
          testCase.tags.forEach(tag => {
            if (!testSuiteTagExpressions.has(tag.tagExpression.toLowerCase())) {
              lines.push(`  ${tag.tagExpression}`)
            }
          })
        }

        lines.push(`  Scenario: [${testCase.title}] ${testCase.description}`)
        gherkinSteps.forEach(step => {
          lines.push(`    ${step}`)
        })
        scenarioCount++
      }
    }
  })

  return lines.join('\n') + '\n'
}

export async function deleteFeatureFile(testSuiteId: string): Promise<boolean> {
  try {
    await ensureAutomationWorkspaceReady()
    const [testSuite, allModules] = await Promise.all([
      prisma.testSuite.findUnique({
        where: { id: testSuiteId },
        include: {
          module: true,
        },
      }),
      prisma.module.findMany(),
    ])

    if (!testSuite) {
      return false
    }

    const modulePath = buildModulePath(allModules, testSuite.module)
    const safeFileName = getTestSuiteFilesystemKey(testSuite.name)

    const featuresBaseDir = getAutomationFeaturesDir()
    const moduleDir = join(featuresBaseDir, modulePath.substring(1))
    const featureFilePath = join(moduleDir, `${safeFileName}.feature`)

    try {
      await fs.unlink(featureFilePath)
      await removeEmptyDirectoriesUp(moduleDir, featuresBaseDir)
      return true
    } catch (error: unknown) {
      if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT') {
        return false
      }
      throw error
    }
  } catch (error) {
    console.error('Error deleting feature file:', error)
    throw error
  }
}

export async function regenerateAllFeatureFiles(): Promise<string[]> {
  try {
    await ensureAutomationWorkspaceReady()
    const featuresBaseDir = getAutomationFeaturesDir()

    try {
      await fs.rm(featuresBaseDir, { recursive: true, force: true })
    } catch (error) {
      console.warn('Could not clear features directory:', error)
    }

    await fs.mkdir(featuresBaseDir, { recursive: true })

    const testSuites = await prisma.testSuite.findMany({
      include: {
        testCases: {
          include: {
            steps: {
              include: {
                parameters: true,
              },
              orderBy: {
                order: 'asc',
              },
            },
            tags: true,
          },
        },
        module: true,
        tags: true,
      },
    })

    const allModules = await prisma.module.findMany()
    const generatedFiles: string[] = []

    for (const testSuite of testSuites) {
      try {
        const modulePath = buildModulePath(allModules, testSuite.module)
        const featureContent = generateFeatureContent(
          testSuite.description || testSuite.name,
          testSuite.testCases,
          testSuite.tags,
        )

        const moduleDir = join(featuresBaseDir, modulePath.substring(1))
        await fs.mkdir(moduleDir, { recursive: true })

        const safeFileName = getTestSuiteFilesystemKey(testSuite.name)
        const featureFilePath = join(moduleDir, `${safeFileName}.feature`)

        await fs.writeFile(featureFilePath, featureContent, 'utf8')
        generatedFiles.push(featureFilePath)
      } catch (error) {
        console.error(`Error generating feature file for test suite ${testSuite.name}:`, error)
      }
    }

    return generatedFiles
  } catch (error) {
    console.error('Error during feature files regeneration:', error)
    throw error
  }
}
