# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

@ts_5ef2a4b707ac67c3
@e2e-smoke
Feature: Seeded suite for E2E feature generation

  @tc_e9c3bfce977c7242
  Scenario: [E2E From Template Case] Reusable login flow for E2E
    Given I open the seeded page

  Scenario: [E2E seeded login works] Seeded login smoke case
    Given I open the seeded page
