# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

@auth
@ts_0f27b215d17bf42e
Feature: Verify user login flows

