# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

@ts_0f27b215d17bf42e
@auth
Feature: Verify user login flows

  @tc_5318c12b81d85810
  Scenario: [test] asdasd
    Given the user navigates to the base url of the selected environment
    When the user fills in the "Email" input field with value "demo@example.com"
    And the user fills in the "Password" input field with value "test1234"
    And the user clicks on the "Login" element
