# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

@auth
@ts_06f2b86636b19c4d
Feature: Tests validating the auth feature

  @tc_dc6f8afe1c80b9dc
  @demo
  Scenario: [Demo Run With Template] Demo run using a template test case
    Given the user navigates to the base url of the selected environment
    When the user fills in the "Email" input field with value "demo@example.com"
    And the user fills in the "Password" input field with value "test1234"
    And the user clicks on the "Login" element
    And the user waits for the route "/home" to be loaded
    Then the element "Title" should true contain the text "Welcome to Home Page"

  @tc_9dea359d462f1430
  Scenario: [Demo Run Without Template] Test case prepared without template
    Given the user navigates to the base url of the selected environment
    When the user fills in the "Email" input field with value "demo@example.com"
    And the user fills in the "Password" input field with value "test1234"
    And the user clicks on the "Login" element
    And the user waits for the route "/home" to be loaded
    Then the url route should be equal to "/home"
    And the element "Title" should true contain the text "Welcome to Home Page"
