import { createHash } from 'node:crypto'
import ts from 'typescript'
import { z } from 'zod'

import type { PrismaClient } from '@prisma/client'
import {
  canonicalStepDefinitionJson,
  stepDefinitionContentHash,
  stepDefinitionSchema,
  type StepDefinition,
} from '../../../packages/cucumber-runtime/src/step-definitions/index.ts'
import { ServiceError } from '@/services/shared/errors'

const MAX_SOURCE_BYTES = 65_536
const forbiddenGlobals = new Set([
  'Bun',
  'Deno',
  'eval',
  'fetch',
  'Function',
  'global',
  'globalThis',
  'module',
  'process',
  'require',
  'WebAssembly',
  'Worker',
  'XMLHttpRequest',
])

const stepDefinitionArtifactInputSchema = z.object({
  handlerSource: z
    .string()
    .min(1)
    .refine(value => Buffer.byteLength(value) <= MAX_SOURCE_BYTES, 'Source is too large.'),
  examples: z.array(z.object({ name: z.string().min(1).max(200), inputs: z.record(z.string(), z.unknown()) })).max(20),
})

const runtimeCapabilityImports: Record<string, readonly string[]> = {
  browser: ['@playwright/test'],
  api: [],
  node: [],
  database: [],
}

function typeFor(input: StepDefinition['inputs'][number] | StepDefinition['outputs'][number]) {
  if (input.type === 'number') return 'number'
  if (input.type === 'boolean') return 'boolean'
  if (input.type === 'json') return 'unknown'
  return 'string'
}

export function generateStepDefinitionContract(definition: StepDefinition) {
  const fields = (values: StepDefinition['inputs'] | StepDefinition['outputs']) =>
    values
      .map(value => `  readonly ${value.name}${'required' in value && !value.required ? '?' : ''}: ${typeFor(value)}`)
      .join('\n')
  return [
    '// Generated by AppraiseJS. Changes will be overwritten.',
    `export interface StepInput {\n${fields(definition.inputs)}\n}`,
    `export interface StepOutput {\n${fields(definition.outputs)}\n}`,
    'export interface StepContext {',
    `  readonly runtime: '${definition.execution.kind === 'reviewed-extension' ? definition.execution.runtime : 'node'}'`,
    '  readonly signal: AbortSignal',
    '}',
    'export type StepHandler = (input: StepInput, context: StepContext) => Promise<StepOutput>',
    '',
  ].join('\n')
}

export function generateStepDefinitionHandlerBoilerplate(definition: StepDefinition) {
  const outputs = definition.outputs.map(output => `${output.name}: undefined as never`).join(', ')
  return [
    "import type { StepHandler } from './contract.js'",
    '',
    'export const handler: StepHandler = async (input, context) => {',
    '  void input',
    '  context.signal.throwIfAborted()',
    '  // Implement the reviewed behavior here.',
    `  return { ${outputs} }`,
    '}',
    '',
  ].join('\n')
}

function inspectSource(source: string, runtime: string) {
  const sourceFile = ts.createSourceFile('handler.ts', source, ts.ScriptTarget.ES2022, true, ts.ScriptKind.TS)
  const issues: string[] = []
  const allowedImports = new Set(['./contract.js', ...(runtimeCapabilityImports[runtime] ?? [])])
  const importIssue = (node: ts.Node) => {
    if (!ts.isImportDeclaration(node) || !ts.isStringLiteral(node.moduleSpecifier)) return null
    return allowedImports.has(node.moduleSpecifier.text)
      ? null
      : `Import "${node.moduleSpecifier.text}" is not allowed by the declared runtime.`
  }
  const globalIssue = (node: ts.Node) => {
    if (!ts.isIdentifier(node) || !forbiddenGlobals.has(node.text)) return null
    if (ts.isPropertyAccessExpression(node.parent) && node.parent.name === node) return null
    return `Global "${node.text}" is not allowed.`
  }
  const inspectNode = (node: ts.Node) =>
    [
      importIssue(node),
      ts.isCallExpression(node) && node.expression.kind === ts.SyntaxKind.ImportKeyword
        ? 'Dynamic imports are not allowed.'
        : null,
      ts.isMetaProperty(node) ? 'import.meta is not allowed.' : null,
      globalIssue(node),
    ].filter((issue): issue is string => Boolean(issue))
  const visit = (node: ts.Node) => {
    issues.push(...inspectNode(node))
    ts.forEachChild(node, visit)
  }
  visit(sourceFile)
  return { sourceFile, issues: [...new Set(issues)] }
}

function compileSource(source: string, runtime: string) {
  const inspected = inspectSource(source, runtime)
  if (inspected.issues.length) return { compiledSource: null, diagnostics: inspected.issues }
  const result = ts.transpileModule(source, {
    fileName: 'handler.ts',
    reportDiagnostics: true,
    compilerOptions: {
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.NodeNext,
      moduleResolution: ts.ModuleResolutionKind.NodeNext,
      isolatedModules: true,
      sourceMap: false,
    },
  })
  const diagnostics = (result.diagnostics ?? [])
    .filter(item => item.category === ts.DiagnosticCategory.Error)
    .map(item => ts.flattenDiagnosticMessageText(item.messageText, '\n'))
  return { compiledSource: diagnostics.length ? null : result.outputText, diagnostics }
}

function artifactManifest(definition: StepDefinition, sourceHash: string, contractHash: string) {
  if (definition.execution.kind !== 'reviewed-extension')
    throw new ServiceError('A reviewed-extension binding is required.', 'VALIDATION')
  return {
    schemaVersion: '1',
    extension: { id: definition.execution.extensionId, version: definition.execution.extensionVersion },
    exportName: definition.execution.exportName,
    runtime: definition.execution.runtime,
    capabilities: [...definition.intent.capabilities].sort(),
    sourceHash,
    contractHash,
  }
}

export class StepDefinitionExtensionService {
  constructor(private readonly database: PrismaClient) {}

  async saveDraftArtifact(draftId: string, expectedRevision: number, value: unknown) {
    const input = stepDefinitionArtifactInputSchema.parse(value)
    const draft = await this.database.stepDefinitionDraft.findUnique({ where: { id: draftId } })
    if (!draft) throw new ServiceError(`Step Definition draft ${draftId} was not found.`, 'NOT_FOUND')
    if (draft.revision !== expectedRevision)
      throw new ServiceError(`Step Definition draft ${draftId} revision is stale.`, 'CONFLICT')
    const definition = stepDefinitionSchema.parse(JSON.parse(draft.draftJson))
    const contractSource = generateStepDefinitionContract(definition)
    const sourceHash = stepDefinitionContentHash(input.handlerSource)
    const manifest = artifactManifest(definition, sourceHash, stepDefinitionContentHash(contractSource))
    return this.database.stepDefinitionDraftArtifact.upsert({
      where: { draftId },
      create: {
        draftId,
        contractSource,
        handlerSource: input.handlerSource,
        examplesJson: canonicalStepDefinitionJson(input.examples),
        manifestJson: canonicalStepDefinitionJson(manifest),
        sourceHash,
      },
      update: {
        contractSource,
        handlerSource: input.handlerSource,
        examplesJson: canonicalStepDefinitionJson(input.examples),
        manifestJson: canonicalStepDefinitionJson(manifest),
        sourceHash,
        compiledSource: null,
        compiledHash: null,
        diagnosticsJson: null,
        conformanceJson: null,
        conformanceHash: null,
        reviewedArtifactHash: null,
      },
    })
  }

  async compileDraftArtifact(draftId: string, expectedRevision: number) {
    const artifact = await this.database.stepDefinitionDraftArtifact.findUnique({
      where: { draftId },
      include: { draft: true },
    })
    if (!artifact) throw new ServiceError('Handler source has not been saved.', 'VALIDATION')
    if (artifact.draft.revision !== expectedRevision)
      throw new ServiceError(`Step Definition draft ${draftId} revision is stale.`, 'CONFLICT')
    const definition = stepDefinitionSchema.parse(JSON.parse(artifact.draft.draftJson))
    if (definition.execution.kind !== 'reviewed-extension')
      throw new ServiceError('A reviewed-extension binding is required.', 'VALIDATION')
    const result = compileSource(artifact.handlerSource, definition.execution.runtime)
    const compiledHash = result.compiledSource ? stepDefinitionContentHash(result.compiledSource) : null
    const examples = JSON.parse(artifact.examplesJson) as unknown[]
    const conformance = {
      passed: Boolean(result.compiledSource) && examples.length > 0,
      checks: [
        { id: 'static-policy', passed: result.diagnostics.length === 0 },
        { id: 'typescript-compile', passed: Boolean(result.compiledSource) },
        { id: 'explicit-examples', passed: examples.length > 0 },
      ],
    }
    const conformanceHash = stepDefinitionContentHash(conformance)
    const updated = await this.database.stepDefinitionDraftArtifact.update({
      where: { draftId },
      data: {
        compiledSource: result.compiledSource,
        compiledHash,
        diagnosticsJson: canonicalStepDefinitionJson(result.diagnostics),
        conformanceJson: canonicalStepDefinitionJson(conformance),
        conformanceHash,
      },
    })
    let revision = artifact.draft.revision
    if (compiledHash) {
      const boundDefinition = {
        ...definition,
        execution: { ...definition.execution, sourceHash: artifact.sourceHash, compiledHash },
      }
      const boundJson = canonicalStepDefinitionJson(boundDefinition)
      await this.database.stepDefinitionDraft.update({
        where: { id: draftId },
        data: {
          draftJson: boundJson,
          draftHash: stepDefinitionContentHash(boundDefinition),
          revision: { increment: 1 },
          validationReportJson: null,
          reviewedDraftHash: null,
          reviewedBy: null,
          reviewedAt: null,
        },
      })
      revision += 1
    }
    return { ...updated, revision, diagnostics: result.diagnostics, conformance }
  }

  async readDraftArtifact(draftId: string) {
    const artifact = await this.database.stepDefinitionDraftArtifact.findUnique({ where: { draftId } })
    if (!artifact) return null
    return {
      ...artifact,
      examples: JSON.parse(artifact.examplesJson),
      manifest: JSON.parse(artifact.manifestJson),
      diagnostics: artifact.diagnosticsJson ? JSON.parse(artifact.diagnosticsJson) : [],
      conformance: artifact.conformanceJson ? JSON.parse(artifact.conformanceJson) : null,
    }
  }

  static artifactHash(value: {
    sourceHash: string
    compiledHash: string
    conformanceHash: string
    manifestJson: string
  }) {
    return `sha256:${createHash('sha256').update(canonicalStepDefinitionJson(value)).digest('hex')}`
  }
}
