import type { StepDefinition } from '../../../../packages/cucumber-runtime/src/step-definitions/index'

export type DraftDefinition = StepDefinition

const searchStopWords = new Set(['and', 'for', 'from', 'into', 'that', 'the', 'this', 'with'])

export function stepDefinitionIdFromTitle(title: string) {
  const slug = title
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
  return `custom.${slug || 'untitled'}`
}

export function deriveStepSearchTerms(definition: DraftDefinition) {
  const phrases = [definition.intent.title, definition.intent.description, definition.human.signature]
  const words = phrases
    .join(' ')
    .toLowerCase()
    .match(/[a-z0-9]+/g)
  return [...new Set(words?.filter(word => word.length >= 3 && !searchStopWords.has(word)) ?? [])].slice(0, 40)
}

export function applyManagedStepMetadata(definition: DraftDefinition): DraftDefinition {
  const id = stepDefinitionIdFromTitle(definition.intent.title)
  const runtime =
    definition.execution.kind === 'reviewed-extension' || definition.execution.kind === 'operation'
      ? definition.execution.runtime
      : 'node'
  return {
    ...definition,
    identity: { ...definition.identity, id, version: '1' },
    intent: { ...definition.intent, capabilities: [runtime], searchTerms: deriveStepSearchTerms(definition) },
    execution:
      definition.execution.kind === 'reviewed-extension'
        ? { ...definition.execution, extensionId: id, extensionVersion: '1' }
        : definition.execution,
  }
}

export function namedPlaceholders(signature: string) {
  return [...signature.matchAll(/\{([a-z][a-zA-Z0-9-]*)\}/g)].map(match => match[1]!)
}

export function reconcileNamedInputs(definition: DraftDefinition, signature: string): DraftDefinition {
  const placeholders = [...new Set(namedPlaceholders(signature))]
  const existing = new Map(definition.inputs.map(input => [input.name, input]))
  const inputs = placeholders.map(
    name =>
      existing.get(name) ?? {
        name,
        label: name,
        description: '',
        type: 'string' as const,
        required: true,
        examples: [],
        aliases: [],
      },
  )
  return {
    ...definition,
    inputs,
    human: {
      ...definition.human,
      signature,
      parameterBindings: placeholders.map(name => ({ placeholder: name, input: name })),
    },
  }
}

export function createHumanStepDraft(now = new Date().toISOString()): DraftDefinition {
  const emptyHash = `sha256:${'0'.repeat(64)}` as const
  return {
    schemaVersion: '1',
    identity: { id: 'custom.untitled', version: '1', status: 'draft' },
    provenance: { creationMethod: 'human-form', createdBy: 'local-user', createdAt: now },
    intent: {
      title: '',
      description: '',
      capabilities: ['node'],
      searchTerms: [],
      examples: ['Describe one intended use.'],
    },
    inputs: [],
    outputs: [],
    human: {
      signature: '',
      keywordCompatibility: ['When'],
      parameterBindings: [],
      groupId: '',
    },
    agent: {
      summary: 'Perform the reusable behavior.',
      usageGuidance: 'Use when this exact reusable behavior is required.',
      examples: [{ intent: 'Use the reusable behavior', inputs: {} }],
    },
    execution: {
      kind: 'reviewed-extension',
      extensionId: 'custom.untitled',
      extensionVersion: '1',
      exportName: 'handler',
      sourceHash: emptyHash,
      compiledHash: emptyHash,
      runtime: 'node',
    },
    lifecycle: {},
  }
}

function contractType(input: DraftDefinition['inputs'][number] | DraftDefinition['outputs'][number]) {
  if (input.type === 'number') return 'number'
  if (input.type === 'boolean') return 'boolean'
  if (input.type === 'json') return 'unknown'
  return 'string'
}

// fallow-ignore-next-line code-duplication -- Client-safe projection mirrors the server generator without importing server dependencies.
export function draftContractSource(definition: DraftDefinition) {
  const fields = (values: DraftDefinition['inputs'] | DraftDefinition['outputs']) =>
    values
      .map(
        value => `  readonly ${value.name}${'required' in value && !value.required ? '?' : ''}: ${contractType(value)}`,
      )
      .join('\n')
  return [
    '// Generated by AppraiseJS. Changes will be overwritten.',
    `export interface StepInput {\n${fields(definition.inputs)}\n}`,
    `export interface StepOutput {\n${fields(definition.outputs)}\n}`,
    'export interface StepContext {',
    `  readonly runtime: '${definition.execution.kind === 'reviewed-extension' ? definition.execution.runtime : 'node'}'`,
    '  readonly signal: AbortSignal',
    '}',
    'export type StepHandler = (input: StepInput, context: StepContext) => Promise<StepOutput>',
    '',
  ].join('\n')
}

export function draftHandlerBoilerplate(definition: DraftDefinition) {
  const outputs = definition.outputs.map(output => `${output.name}: undefined as never`).join(', ')
  return [
    "import type { StepHandler } from './contract.js'",
    '',
    'export const handler: StepHandler = async (input, context) => {',
    '  void input',
    '  context.signal.throwIfAborted()',
    '  // Implement the reviewed behavior here.',
    `  return { ${outputs} }`,
    '}',
    '',
  ].join('\n')
}
