# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# This file is automatically generated from Test Suite data.
# Any manual changes will be overwritten when the Test Suite is updated.
# To modify this feature, update the corresponding Test Suite in the application.

@ts_280de079298c199f
Feature: Demo tests

  @tc_95be4693317298de
  Scenario: [Login 2] Login Test Flow 2
    Given the user navigates to the base url of the selected environment
    When the user fills in the "Email" input field with value "demo@example.com"
    And the user fills in the "Password" input field with value "test1234"
    And the user clicks on the "Login Button" element
    And the user waits for the route "/home" to be loaded
    Then the element "Welcome to Home Page" should true contain the text "Welcome to Home Page"

  @tc_7bf77452b93da68b
  Scenario: [test] asdasd
    Given the user navigates to the base url of the selected environment
    When the user fills in the "Email" input field with value "test@test.com"
    And the user clicks on the "Login Button" element
